// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type traceguardDNSCompatConnectionDedupeKey struct {
	_         structs.HostLayout
	Pid       uint32
	Port      uint16
	LocalPort uint16
	Family    uint8
	Protocol  uint8
	Direction uint8
	Pad       uint8
	Addr      [16]uint8
	LocalAddr [16]uint8
}

type traceguardDNSCompatConnectionDedupeValue struct {
	_          structs.HostLayout
	LastSeenNs uint64
}

type traceguardDNSCompatDomainKey struct {
	_      structs.HostLayout
	Domain [256]uint8
}

type traceguardDNSCompatEndpoint4CidrKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [7]uint8
	_         [1]byte
}

type traceguardDNSCompatEndpoint4Key struct {
	_         structs.HostLayout
	Addr      uint32
	Port      uint16
	Transport uint8
	Pad       uint8
}

type traceguardDNSCompatEndpoint6CidrKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [19]uint8
	_         [1]byte
}

type traceguardDNSCompatEndpoint6Key struct {
	_         structs.HostLayout
	Addr      [16]uint8
	Port      uint16
	Transport uint8
	Pad       uint8
}

type traceguardDNSCompatListenerInfoKey struct {
	_        structs.HostLayout
	Port     uint16
	Family   uint8
	Protocol uint8
	Addr     [16]uint8
}

type traceguardDNSCompatListenerInfoValue struct {
	_    structs.HostLayout
	Pid  uint32
	Comm [16]int8
}

type traceguardDNSCompatSettings struct {
	_                 structs.HostLayout
	BlockEnabled      uint8
	BlockAllDomains   uint8
	BlockAllResolvers uint8
	Pad               [5]uint8
}

type traceguardDNSCompatSocketInfoKey struct {
	_        structs.HostLayout
	Pid      uint32
	Port     uint16
	Family   uint8
	Protocol uint8
	Addr     [16]uint8
}

type traceguardDNSCompatSocketInfoValue struct {
	_        structs.HostLayout
	Comm     [16]int8
	Hook     uint8
	Family   uint8
	Protocol uint8
	Pad      uint8
}

// loadTraceguardDNSCompat returns the embedded CollectionSpec for traceguardDNSCompat.
func loadTraceguardDNSCompat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TraceguardDNSCompatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load traceguardDNSCompat: %w", err)
	}

	return spec, err
}

// loadTraceguardDNSCompatObjects loads traceguardDNSCompat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*traceguardDNSCompatObjects
//	*traceguardDNSCompatPrograms
//	*traceguardDNSCompatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTraceguardDNSCompatObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTraceguardDNSCompat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// traceguardDNSCompatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardDNSCompatSpecs struct {
	traceguardDNSCompatProgramSpecs
	traceguardDNSCompatMapSpecs
	traceguardDNSCompatVariableSpecs
}

// traceguardDNSCompatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardDNSCompatProgramSpecs struct {
	TraceConnect4          *ebpf.ProgramSpec `ebpf:"trace_connect4"`
	TraceConnect6          *ebpf.ProgramSpec `ebpf:"trace_connect6"`
	TraceConnectionIngress *ebpf.ProgramSpec `ebpf:"trace_connection_ingress"`
	TraceDns               *ebpf.ProgramSpec `ebpf:"trace_dns"`
	TraceExecve            *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceExecveat          *ebpf.ProgramSpec `ebpf:"trace_execveat"`
	TracePostBind4         *ebpf.ProgramSpec `ebpf:"trace_post_bind4"`
	TracePostBind6         *ebpf.ProgramSpec `ebpf:"trace_post_bind6"`
	TraceRecvmsg4          *ebpf.ProgramSpec `ebpf:"trace_recvmsg4"`
	TraceRecvmsg6          *ebpf.ProgramSpec `ebpf:"trace_recvmsg6"`
	TraceSendmsg4          *ebpf.ProgramSpec `ebpf:"trace_sendmsg4"`
	TraceSendmsg6          *ebpf.ProgramSpec `ebpf:"trace_sendmsg6"`
}

// traceguardDNSCompatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardDNSCompatMapSpecs struct {
	Allowlist               *ebpf.MapSpec `ebpf:"allowlist"`
	Blocklist               *ebpf.MapSpec `ebpf:"blocklist"`
	ConnectionDedupe        *ebpf.MapSpec `ebpf:"connection_dedupe"`
	Endpoint4AllowRules     *ebpf.MapSpec `ebpf:"endpoint4_allow_rules"`
	Endpoint4CidrAllowRules *ebpf.MapSpec `ebpf:"endpoint4_cidr_allow_rules"`
	Endpoint4CidrRules      *ebpf.MapSpec `ebpf:"endpoint4_cidr_rules"`
	Endpoint4Rules          *ebpf.MapSpec `ebpf:"endpoint4_rules"`
	Endpoint6AllowRules     *ebpf.MapSpec `ebpf:"endpoint6_allow_rules"`
	Endpoint6CidrAllowRules *ebpf.MapSpec `ebpf:"endpoint6_cidr_allow_rules"`
	Endpoint6CidrRules      *ebpf.MapSpec `ebpf:"endpoint6_cidr_rules"`
	Endpoint6Rules          *ebpf.MapSpec `ebpf:"endpoint6_rules"`
	Events                  *ebpf.MapSpec `ebpf:"events"`
	ListenerInfo            *ebpf.MapSpec `ebpf:"listener_info"`
	Settings                *ebpf.MapSpec `ebpf:"settings"`
	SocketInfo              *ebpf.MapSpec `ebpf:"socket_info"`
}

// traceguardDNSCompatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardDNSCompatVariableSpecs struct {
}

// traceguardDNSCompatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardDNSCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardDNSCompatObjects struct {
	traceguardDNSCompatPrograms
	traceguardDNSCompatMaps
	traceguardDNSCompatVariables
}

func (o *traceguardDNSCompatObjects) Close() error {
	return _TraceguardDNSCompatClose(
		&o.traceguardDNSCompatPrograms,
		&o.traceguardDNSCompatMaps,
	)
}

// traceguardDNSCompatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardDNSCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardDNSCompatMaps struct {
	Allowlist               *ebpf.Map `ebpf:"allowlist"`
	Blocklist               *ebpf.Map `ebpf:"blocklist"`
	ConnectionDedupe        *ebpf.Map `ebpf:"connection_dedupe"`
	Endpoint4AllowRules     *ebpf.Map `ebpf:"endpoint4_allow_rules"`
	Endpoint4CidrAllowRules *ebpf.Map `ebpf:"endpoint4_cidr_allow_rules"`
	Endpoint4CidrRules      *ebpf.Map `ebpf:"endpoint4_cidr_rules"`
	Endpoint4Rules          *ebpf.Map `ebpf:"endpoint4_rules"`
	Endpoint6AllowRules     *ebpf.Map `ebpf:"endpoint6_allow_rules"`
	Endpoint6CidrAllowRules *ebpf.Map `ebpf:"endpoint6_cidr_allow_rules"`
	Endpoint6CidrRules      *ebpf.Map `ebpf:"endpoint6_cidr_rules"`
	Endpoint6Rules          *ebpf.Map `ebpf:"endpoint6_rules"`
	Events                  *ebpf.Map `ebpf:"events"`
	ListenerInfo            *ebpf.Map `ebpf:"listener_info"`
	Settings                *ebpf.Map `ebpf:"settings"`
	SocketInfo              *ebpf.Map `ebpf:"socket_info"`
}

func (m *traceguardDNSCompatMaps) Close() error {
	return _TraceguardDNSCompatClose(
		m.Allowlist,
		m.Blocklist,
		m.ConnectionDedupe,
		m.Endpoint4AllowRules,
		m.Endpoint4CidrAllowRules,
		m.Endpoint4CidrRules,
		m.Endpoint4Rules,
		m.Endpoint6AllowRules,
		m.Endpoint6CidrAllowRules,
		m.Endpoint6CidrRules,
		m.Endpoint6Rules,
		m.Events,
		m.ListenerInfo,
		m.Settings,
		m.SocketInfo,
	)
}

// traceguardDNSCompatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardDNSCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardDNSCompatVariables struct {
}

// traceguardDNSCompatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardDNSCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardDNSCompatPrograms struct {
	TraceConnect4          *ebpf.Program `ebpf:"trace_connect4"`
	TraceConnect6          *ebpf.Program `ebpf:"trace_connect6"`
	TraceConnectionIngress *ebpf.Program `ebpf:"trace_connection_ingress"`
	TraceDns               *ebpf.Program `ebpf:"trace_dns"`
	TraceExecve            *ebpf.Program `ebpf:"trace_execve"`
	TraceExecveat          *ebpf.Program `ebpf:"trace_execveat"`
	TracePostBind4         *ebpf.Program `ebpf:"trace_post_bind4"`
	TracePostBind6         *ebpf.Program `ebpf:"trace_post_bind6"`
	TraceRecvmsg4          *ebpf.Program `ebpf:"trace_recvmsg4"`
	TraceRecvmsg6          *ebpf.Program `ebpf:"trace_recvmsg6"`
	TraceSendmsg4          *ebpf.Program `ebpf:"trace_sendmsg4"`
	TraceSendmsg6          *ebpf.Program `ebpf:"trace_sendmsg6"`
}

func (p *traceguardDNSCompatPrograms) Close() error {
	return _TraceguardDNSCompatClose(
		p.TraceConnect4,
		p.TraceConnect6,
		p.TraceConnectionIngress,
		p.TraceDns,
		p.TraceExecve,
		p.TraceExecveat,
		p.TracePostBind4,
		p.TracePostBind6,
		p.TraceRecvmsg4,
		p.TraceRecvmsg6,
		p.TraceSendmsg4,
		p.TraceSendmsg6,
	)
}

func _TraceguardDNSCompatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed traceguarddnscompat_bpfel.o
var _TraceguardDNSCompatBytes []byte
