// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type traceguardDNSCompatConnectionDedupeKey struct {
	_         structs.HostLayout
	Pid       uint32
	Port      uint16
	LocalPort uint16
	Family    uint8
	Protocol  uint8
	Direction uint8
	Pad       uint8
	Addr      [16]uint8
	LocalAddr [16]uint8
}

type traceguardDNSCompatConnectionDedupeValue struct {
	_          structs.HostLayout
	LastSeenNs uint64
}

type traceguardDNSCompatDnsParseResult struct {
	_                structs.HostLayout
	Key              traceguardDNSCompatDomainKey
	QnameLength      uint16
	AllowSuffixMatch uint8
	BlockSuffixMatch uint8
	Pad              [4]uint8
}

type traceguardDNSCompatDomainKey struct {
	_      structs.HostLayout
	Domain [256]uint8
}

type traceguardDNSCompatDomainSuffixKey struct {
	_          structs.HostLayout
	Hash       uint64
	Length     uint16
	PolicySlot uint8
	Pad0       uint8
	Pad1       uint32
}

type traceguardDNSCompatEgress4Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [21]uint8
	Pad       [3]uint8
}

type traceguardDNSCompatEgress6Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [33]uint8
	Pad       [3]uint8
}

type traceguardDNSCompatEndpoint4CidrKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [7]uint8
	Pad       uint8
}

type traceguardDNSCompatEndpoint4Key struct {
	_         structs.HostLayout
	Addr      uint32
	Port      uint16
	Transport uint8
	Pad       uint8
}

type traceguardDNSCompatEndpoint6CidrKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [19]uint8
	Pad       uint8
}

type traceguardDNSCompatEndpoint6Key struct {
	_         structs.HostLayout
	Addr      [16]uint8
	Port      uint16
	Transport uint8
	Pad       uint8
}

type traceguardDNSCompatListenerInfoKey struct {
	_        structs.HostLayout
	Port     uint16
	Family   uint8
	Protocol uint8
	Addr     [16]uint8
}

type traceguardDNSCompatListenerInfoValue struct {
	_    structs.HostLayout
	Pid  uint32
	Comm [16]int8
}

type traceguardDNSCompatSettings struct {
	_                    structs.HostLayout
	BlockEnabled         uint8
	BlockAllDomains      uint8
	BlockAllResolvers    uint8
	AllowSuffixesEnabled uint8
	ActivePolicySlot     uint8
	BlockSuffixesEnabled uint8
	EgressEnabled        uint8
	EgressEnforce        uint8
	EgressDefaultBlock   uint8
	Pad                  [7]uint8
}

type traceguardDNSCompatSocketInfoKey struct {
	_        structs.HostLayout
	Pid      uint32
	Port     uint16
	Family   uint8
	Protocol uint8
	Addr     [16]uint8
}

type traceguardDNSCompatSocketInfoValue struct {
	_        structs.HostLayout
	Comm     [16]int8
	Hook     uint8
	Family   uint8
	Protocol uint8
	Pad      uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	traceguardDNSCompatMapAllowSuffixes           = "allow_suffixes"
	traceguardDNSCompatMapAllowlist               = "allowlist"
	traceguardDNSCompatMapBlockSuffixes           = "block_suffixes"
	traceguardDNSCompatMapBlocklist               = "blocklist"
	traceguardDNSCompatMapConnectionDedupe        = "connection_dedupe"
	traceguardDNSCompatMapDnsScratch              = "dns_scratch"
	traceguardDNSCompatMapEgress4AllowRules       = "egress4_allow_rules"
	traceguardDNSCompatMapEgress4BlockRules       = "egress4_block_rules"
	traceguardDNSCompatMapEgress6AllowRules       = "egress6_allow_rules"
	traceguardDNSCompatMapEgress6BlockRules       = "egress6_block_rules"
	traceguardDNSCompatMapEndpoint4AllowRules     = "endpoint4_allow_rules"
	traceguardDNSCompatMapEndpoint4CidrAllowRules = "endpoint4_cidr_allow_rules"
	traceguardDNSCompatMapEndpoint4CidrRules      = "endpoint4_cidr_rules"
	traceguardDNSCompatMapEndpoint4Rules          = "endpoint4_rules"
	traceguardDNSCompatMapEndpoint6AllowRules     = "endpoint6_allow_rules"
	traceguardDNSCompatMapEndpoint6CidrAllowRules = "endpoint6_cidr_allow_rules"
	traceguardDNSCompatMapEndpoint6CidrRules      = "endpoint6_cidr_rules"
	traceguardDNSCompatMapEndpoint6Rules          = "endpoint6_rules"
	traceguardDNSCompatMapEvents                  = "events"
	traceguardDNSCompatMapListenerInfo            = "listener_info"
	traceguardDNSCompatMapSettings                = "settings"
	traceguardDNSCompatMapSocketInfo              = "socket_info"
	traceguardDNSCompatProgTraceConnect4          = "trace_connect4"
	traceguardDNSCompatProgTraceConnect6          = "trace_connect6"
	traceguardDNSCompatProgTraceConnectionIngress = "trace_connection_ingress"
	traceguardDNSCompatProgTraceCreat             = "trace_creat"
	traceguardDNSCompatProgTraceDns               = "trace_dns"
	traceguardDNSCompatProgTraceExecve            = "trace_execve"
	traceguardDNSCompatProgTraceExecveat          = "trace_execveat"
	traceguardDNSCompatProgTraceOpen              = "trace_open"
	traceguardDNSCompatProgTraceOpenat            = "trace_openat"
	traceguardDNSCompatProgTraceOpenat2           = "trace_openat2"
	traceguardDNSCompatProgTracePostBind4         = "trace_post_bind4"
	traceguardDNSCompatProgTracePostBind6         = "trace_post_bind6"
	traceguardDNSCompatProgTraceRecvmsg4          = "trace_recvmsg4"
	traceguardDNSCompatProgTraceRecvmsg6          = "trace_recvmsg6"
	traceguardDNSCompatProgTraceSendmsg4          = "trace_sendmsg4"
	traceguardDNSCompatProgTraceSendmsg6          = "trace_sendmsg6"
)

// loadTraceguardDNSCompat returns the embedded CollectionSpec for traceguardDNSCompat.
func loadTraceguardDNSCompat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TraceguardDNSCompatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load traceguardDNSCompat: %w", err)
	}

	return spec, err
}

// loadTraceguardDNSCompatObjects loads traceguardDNSCompat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*traceguardDNSCompatObjects
//	*traceguardDNSCompatPrograms
//	*traceguardDNSCompatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTraceguardDNSCompatObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTraceguardDNSCompat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// traceguardDNSCompatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardDNSCompatSpecs struct {
	traceguardDNSCompatProgramSpecs
	traceguardDNSCompatMapSpecs
	traceguardDNSCompatVariableSpecs
}

// traceguardDNSCompatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardDNSCompatProgramSpecs struct {
	TraceConnect4          *ebpf.ProgramSpec `ebpf:"trace_connect4"`
	TraceConnect6          *ebpf.ProgramSpec `ebpf:"trace_connect6"`
	TraceConnectionIngress *ebpf.ProgramSpec `ebpf:"trace_connection_ingress"`
	TraceCreat             *ebpf.ProgramSpec `ebpf:"trace_creat"`
	TraceDns               *ebpf.ProgramSpec `ebpf:"trace_dns"`
	TraceExecve            *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceExecveat          *ebpf.ProgramSpec `ebpf:"trace_execveat"`
	TraceOpen              *ebpf.ProgramSpec `ebpf:"trace_open"`
	TraceOpenat            *ebpf.ProgramSpec `ebpf:"trace_openat"`
	TraceOpenat2           *ebpf.ProgramSpec `ebpf:"trace_openat2"`
	TracePostBind4         *ebpf.ProgramSpec `ebpf:"trace_post_bind4"`
	TracePostBind6         *ebpf.ProgramSpec `ebpf:"trace_post_bind6"`
	TraceRecvmsg4          *ebpf.ProgramSpec `ebpf:"trace_recvmsg4"`
	TraceRecvmsg6          *ebpf.ProgramSpec `ebpf:"trace_recvmsg6"`
	TraceSendmsg4          *ebpf.ProgramSpec `ebpf:"trace_sendmsg4"`
	TraceSendmsg6          *ebpf.ProgramSpec `ebpf:"trace_sendmsg6"`
}

// traceguardDNSCompatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardDNSCompatMapSpecs struct {
	AllowSuffixes           *ebpf.MapSpec `ebpf:"allow_suffixes"`
	Allowlist               *ebpf.MapSpec `ebpf:"allowlist"`
	BlockSuffixes           *ebpf.MapSpec `ebpf:"block_suffixes"`
	Blocklist               *ebpf.MapSpec `ebpf:"blocklist"`
	ConnectionDedupe        *ebpf.MapSpec `ebpf:"connection_dedupe"`
	DnsScratch              *ebpf.MapSpec `ebpf:"dns_scratch"`
	Egress4AllowRules       *ebpf.MapSpec `ebpf:"egress4_allow_rules"`
	Egress4BlockRules       *ebpf.MapSpec `ebpf:"egress4_block_rules"`
	Egress6AllowRules       *ebpf.MapSpec `ebpf:"egress6_allow_rules"`
	Egress6BlockRules       *ebpf.MapSpec `ebpf:"egress6_block_rules"`
	Endpoint4AllowRules     *ebpf.MapSpec `ebpf:"endpoint4_allow_rules"`
	Endpoint4CidrAllowRules *ebpf.MapSpec `ebpf:"endpoint4_cidr_allow_rules"`
	Endpoint4CidrRules      *ebpf.MapSpec `ebpf:"endpoint4_cidr_rules"`
	Endpoint4Rules          *ebpf.MapSpec `ebpf:"endpoint4_rules"`
	Endpoint6AllowRules     *ebpf.MapSpec `ebpf:"endpoint6_allow_rules"`
	Endpoint6CidrAllowRules *ebpf.MapSpec `ebpf:"endpoint6_cidr_allow_rules"`
	Endpoint6CidrRules      *ebpf.MapSpec `ebpf:"endpoint6_cidr_rules"`
	Endpoint6Rules          *ebpf.MapSpec `ebpf:"endpoint6_rules"`
	Events                  *ebpf.MapSpec `ebpf:"events"`
	ListenerInfo            *ebpf.MapSpec `ebpf:"listener_info"`
	Settings                *ebpf.MapSpec `ebpf:"settings"`
	SocketInfo              *ebpf.MapSpec `ebpf:"socket_info"`
}

// traceguardDNSCompatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardDNSCompatVariableSpecs struct {
}

// traceguardDNSCompatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardDNSCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardDNSCompatObjects struct {
	traceguardDNSCompatPrograms
	traceguardDNSCompatMaps
	traceguardDNSCompatVariables
}

func (o *traceguardDNSCompatObjects) Close() error {
	return _TraceguardDNSCompatClose(
		&o.traceguardDNSCompatPrograms,
		&o.traceguardDNSCompatMaps,
	)
}

// traceguardDNSCompatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardDNSCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardDNSCompatMaps struct {
	AllowSuffixes           *ebpf.Map `ebpf:"allow_suffixes"`
	Allowlist               *ebpf.Map `ebpf:"allowlist"`
	BlockSuffixes           *ebpf.Map `ebpf:"block_suffixes"`
	Blocklist               *ebpf.Map `ebpf:"blocklist"`
	ConnectionDedupe        *ebpf.Map `ebpf:"connection_dedupe"`
	DnsScratch              *ebpf.Map `ebpf:"dns_scratch"`
	Egress4AllowRules       *ebpf.Map `ebpf:"egress4_allow_rules"`
	Egress4BlockRules       *ebpf.Map `ebpf:"egress4_block_rules"`
	Egress6AllowRules       *ebpf.Map `ebpf:"egress6_allow_rules"`
	Egress6BlockRules       *ebpf.Map `ebpf:"egress6_block_rules"`
	Endpoint4AllowRules     *ebpf.Map `ebpf:"endpoint4_allow_rules"`
	Endpoint4CidrAllowRules *ebpf.Map `ebpf:"endpoint4_cidr_allow_rules"`
	Endpoint4CidrRules      *ebpf.Map `ebpf:"endpoint4_cidr_rules"`
	Endpoint4Rules          *ebpf.Map `ebpf:"endpoint4_rules"`
	Endpoint6AllowRules     *ebpf.Map `ebpf:"endpoint6_allow_rules"`
	Endpoint6CidrAllowRules *ebpf.Map `ebpf:"endpoint6_cidr_allow_rules"`
	Endpoint6CidrRules      *ebpf.Map `ebpf:"endpoint6_cidr_rules"`
	Endpoint6Rules          *ebpf.Map `ebpf:"endpoint6_rules"`
	Events                  *ebpf.Map `ebpf:"events"`
	ListenerInfo            *ebpf.Map `ebpf:"listener_info"`
	Settings                *ebpf.Map `ebpf:"settings"`
	SocketInfo              *ebpf.Map `ebpf:"socket_info"`
}

func (m *traceguardDNSCompatMaps) Close() error {
	return _TraceguardDNSCompatClose(
		m.AllowSuffixes,
		m.Allowlist,
		m.BlockSuffixes,
		m.Blocklist,
		m.ConnectionDedupe,
		m.DnsScratch,
		m.Egress4AllowRules,
		m.Egress4BlockRules,
		m.Egress6AllowRules,
		m.Egress6BlockRules,
		m.Endpoint4AllowRules,
		m.Endpoint4CidrAllowRules,
		m.Endpoint4CidrRules,
		m.Endpoint4Rules,
		m.Endpoint6AllowRules,
		m.Endpoint6CidrAllowRules,
		m.Endpoint6CidrRules,
		m.Endpoint6Rules,
		m.Events,
		m.ListenerInfo,
		m.Settings,
		m.SocketInfo,
	)
}

// traceguardDNSCompatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardDNSCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardDNSCompatVariables struct {
}

// traceguardDNSCompatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardDNSCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardDNSCompatPrograms struct {
	TraceConnect4          *ebpf.Program `ebpf:"trace_connect4"`
	TraceConnect6          *ebpf.Program `ebpf:"trace_connect6"`
	TraceConnectionIngress *ebpf.Program `ebpf:"trace_connection_ingress"`
	TraceCreat             *ebpf.Program `ebpf:"trace_creat"`
	TraceDns               *ebpf.Program `ebpf:"trace_dns"`
	TraceExecve            *ebpf.Program `ebpf:"trace_execve"`
	TraceExecveat          *ebpf.Program `ebpf:"trace_execveat"`
	TraceOpen              *ebpf.Program `ebpf:"trace_open"`
	TraceOpenat            *ebpf.Program `ebpf:"trace_openat"`
	TraceOpenat2           *ebpf.Program `ebpf:"trace_openat2"`
	TracePostBind4         *ebpf.Program `ebpf:"trace_post_bind4"`
	TracePostBind6         *ebpf.Program `ebpf:"trace_post_bind6"`
	TraceRecvmsg4          *ebpf.Program `ebpf:"trace_recvmsg4"`
	TraceRecvmsg6          *ebpf.Program `ebpf:"trace_recvmsg6"`
	TraceSendmsg4          *ebpf.Program `ebpf:"trace_sendmsg4"`
	TraceSendmsg6          *ebpf.Program `ebpf:"trace_sendmsg6"`
}

func (p *traceguardDNSCompatPrograms) Close() error {
	return _TraceguardDNSCompatClose(
		p.TraceConnect4,
		p.TraceConnect6,
		p.TraceConnectionIngress,
		p.TraceCreat,
		p.TraceDns,
		p.TraceExecve,
		p.TraceExecveat,
		p.TraceOpen,
		p.TraceOpenat,
		p.TraceOpenat2,
		p.TracePostBind4,
		p.TracePostBind6,
		p.TraceRecvmsg4,
		p.TraceRecvmsg6,
		p.TraceSendmsg4,
		p.TraceSendmsg6,
	)
}

func _TraceguardDNSCompatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed traceguarddnscompat_bpfeb.o
var _TraceguardDNSCompatBytes []byte
