// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type traceguardRecvmsgCompatConnectionDedupeKey struct {
	_         structs.HostLayout
	Pid       uint32
	Port      uint16
	LocalPort uint16
	Family    uint8
	Protocol  uint8
	Direction uint8
	Pad       uint8
	Addr      [16]uint8
	LocalAddr [16]uint8
}

type traceguardRecvmsgCompatConnectionDedupeValue struct {
	_          structs.HostLayout
	LastSeenNs uint64
}

type traceguardRecvmsgCompatDomainKey struct {
	_      structs.HostLayout
	Domain [256]uint8
}

type traceguardRecvmsgCompatEndpoint4CidrKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [7]uint8
	_         [1]byte
}

type traceguardRecvmsgCompatEndpoint4Key struct {
	_         structs.HostLayout
	Addr      uint32
	Port      uint16
	Transport uint8
	Pad       uint8
}

type traceguardRecvmsgCompatEndpoint6CidrKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [19]uint8
	_         [1]byte
}

type traceguardRecvmsgCompatEndpoint6Key struct {
	_         structs.HostLayout
	Addr      [16]uint8
	Port      uint16
	Transport uint8
	Pad       uint8
}

type traceguardRecvmsgCompatListenerInfoKey struct {
	_        structs.HostLayout
	Port     uint16
	Family   uint8
	Protocol uint8
	Addr     [16]uint8
}

type traceguardRecvmsgCompatListenerInfoValue struct {
	_    structs.HostLayout
	Pid  uint32
	Comm [16]int8
}

type traceguardRecvmsgCompatSettings struct {
	_                 structs.HostLayout
	BlockEnabled      uint8
	BlockAllDomains   uint8
	BlockAllResolvers uint8
	Pad               [5]uint8
}

type traceguardRecvmsgCompatSocketInfoKey struct {
	_        structs.HostLayout
	Pid      uint32
	Port     uint16
	Family   uint8
	Protocol uint8
	Addr     [16]uint8
}

type traceguardRecvmsgCompatSocketInfoValue struct {
	_        structs.HostLayout
	Comm     [16]int8
	Hook     uint8
	Family   uint8
	Protocol uint8
	Pad      uint8
}

// loadTraceguardRecvmsgCompat returns the embedded CollectionSpec for traceguardRecvmsgCompat.
func loadTraceguardRecvmsgCompat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TraceguardRecvmsgCompatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load traceguardRecvmsgCompat: %w", err)
	}

	return spec, err
}

// loadTraceguardRecvmsgCompatObjects loads traceguardRecvmsgCompat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*traceguardRecvmsgCompatObjects
//	*traceguardRecvmsgCompatPrograms
//	*traceguardRecvmsgCompatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTraceguardRecvmsgCompatObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTraceguardRecvmsgCompat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// traceguardRecvmsgCompatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardRecvmsgCompatSpecs struct {
	traceguardRecvmsgCompatProgramSpecs
	traceguardRecvmsgCompatMapSpecs
	traceguardRecvmsgCompatVariableSpecs
}

// traceguardRecvmsgCompatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardRecvmsgCompatProgramSpecs struct {
	TraceConnect4          *ebpf.ProgramSpec `ebpf:"trace_connect4"`
	TraceConnect6          *ebpf.ProgramSpec `ebpf:"trace_connect6"`
	TraceConnectionIngress *ebpf.ProgramSpec `ebpf:"trace_connection_ingress"`
	TraceDns               *ebpf.ProgramSpec `ebpf:"trace_dns"`
	TraceExecve            *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceExecveat          *ebpf.ProgramSpec `ebpf:"trace_execveat"`
	TracePostBind4         *ebpf.ProgramSpec `ebpf:"trace_post_bind4"`
	TracePostBind6         *ebpf.ProgramSpec `ebpf:"trace_post_bind6"`
	TraceRecvmsg4          *ebpf.ProgramSpec `ebpf:"trace_recvmsg4"`
	TraceRecvmsg6          *ebpf.ProgramSpec `ebpf:"trace_recvmsg6"`
	TraceSendmsg4          *ebpf.ProgramSpec `ebpf:"trace_sendmsg4"`
	TraceSendmsg6          *ebpf.ProgramSpec `ebpf:"trace_sendmsg6"`
}

// traceguardRecvmsgCompatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardRecvmsgCompatMapSpecs struct {
	Allowlist               *ebpf.MapSpec `ebpf:"allowlist"`
	Blocklist               *ebpf.MapSpec `ebpf:"blocklist"`
	ConnectionDedupe        *ebpf.MapSpec `ebpf:"connection_dedupe"`
	Endpoint4AllowRules     *ebpf.MapSpec `ebpf:"endpoint4_allow_rules"`
	Endpoint4CidrAllowRules *ebpf.MapSpec `ebpf:"endpoint4_cidr_allow_rules"`
	Endpoint4CidrRules      *ebpf.MapSpec `ebpf:"endpoint4_cidr_rules"`
	Endpoint4Rules          *ebpf.MapSpec `ebpf:"endpoint4_rules"`
	Endpoint6AllowRules     *ebpf.MapSpec `ebpf:"endpoint6_allow_rules"`
	Endpoint6CidrAllowRules *ebpf.MapSpec `ebpf:"endpoint6_cidr_allow_rules"`
	Endpoint6CidrRules      *ebpf.MapSpec `ebpf:"endpoint6_cidr_rules"`
	Endpoint6Rules          *ebpf.MapSpec `ebpf:"endpoint6_rules"`
	Events                  *ebpf.MapSpec `ebpf:"events"`
	ListenerInfo            *ebpf.MapSpec `ebpf:"listener_info"`
	Settings                *ebpf.MapSpec `ebpf:"settings"`
	SocketInfo              *ebpf.MapSpec `ebpf:"socket_info"`
}

// traceguardRecvmsgCompatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardRecvmsgCompatVariableSpecs struct {
}

// traceguardRecvmsgCompatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardRecvmsgCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardRecvmsgCompatObjects struct {
	traceguardRecvmsgCompatPrograms
	traceguardRecvmsgCompatMaps
	traceguardRecvmsgCompatVariables
}

func (o *traceguardRecvmsgCompatObjects) Close() error {
	return _TraceguardRecvmsgCompatClose(
		&o.traceguardRecvmsgCompatPrograms,
		&o.traceguardRecvmsgCompatMaps,
	)
}

// traceguardRecvmsgCompatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardRecvmsgCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardRecvmsgCompatMaps struct {
	Allowlist               *ebpf.Map `ebpf:"allowlist"`
	Blocklist               *ebpf.Map `ebpf:"blocklist"`
	ConnectionDedupe        *ebpf.Map `ebpf:"connection_dedupe"`
	Endpoint4AllowRules     *ebpf.Map `ebpf:"endpoint4_allow_rules"`
	Endpoint4CidrAllowRules *ebpf.Map `ebpf:"endpoint4_cidr_allow_rules"`
	Endpoint4CidrRules      *ebpf.Map `ebpf:"endpoint4_cidr_rules"`
	Endpoint4Rules          *ebpf.Map `ebpf:"endpoint4_rules"`
	Endpoint6AllowRules     *ebpf.Map `ebpf:"endpoint6_allow_rules"`
	Endpoint6CidrAllowRules *ebpf.Map `ebpf:"endpoint6_cidr_allow_rules"`
	Endpoint6CidrRules      *ebpf.Map `ebpf:"endpoint6_cidr_rules"`
	Endpoint6Rules          *ebpf.Map `ebpf:"endpoint6_rules"`
	Events                  *ebpf.Map `ebpf:"events"`
	ListenerInfo            *ebpf.Map `ebpf:"listener_info"`
	Settings                *ebpf.Map `ebpf:"settings"`
	SocketInfo              *ebpf.Map `ebpf:"socket_info"`
}

func (m *traceguardRecvmsgCompatMaps) Close() error {
	return _TraceguardRecvmsgCompatClose(
		m.Allowlist,
		m.Blocklist,
		m.ConnectionDedupe,
		m.Endpoint4AllowRules,
		m.Endpoint4CidrAllowRules,
		m.Endpoint4CidrRules,
		m.Endpoint4Rules,
		m.Endpoint6AllowRules,
		m.Endpoint6CidrAllowRules,
		m.Endpoint6CidrRules,
		m.Endpoint6Rules,
		m.Events,
		m.ListenerInfo,
		m.Settings,
		m.SocketInfo,
	)
}

// traceguardRecvmsgCompatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardRecvmsgCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardRecvmsgCompatVariables struct {
}

// traceguardRecvmsgCompatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardRecvmsgCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardRecvmsgCompatPrograms struct {
	TraceConnect4          *ebpf.Program `ebpf:"trace_connect4"`
	TraceConnect6          *ebpf.Program `ebpf:"trace_connect6"`
	TraceConnectionIngress *ebpf.Program `ebpf:"trace_connection_ingress"`
	TraceDns               *ebpf.Program `ebpf:"trace_dns"`
	TraceExecve            *ebpf.Program `ebpf:"trace_execve"`
	TraceExecveat          *ebpf.Program `ebpf:"trace_execveat"`
	TracePostBind4         *ebpf.Program `ebpf:"trace_post_bind4"`
	TracePostBind6         *ebpf.Program `ebpf:"trace_post_bind6"`
	TraceRecvmsg4          *ebpf.Program `ebpf:"trace_recvmsg4"`
	TraceRecvmsg6          *ebpf.Program `ebpf:"trace_recvmsg6"`
	TraceSendmsg4          *ebpf.Program `ebpf:"trace_sendmsg4"`
	TraceSendmsg6          *ebpf.Program `ebpf:"trace_sendmsg6"`
}

func (p *traceguardRecvmsgCompatPrograms) Close() error {
	return _TraceguardRecvmsgCompatClose(
		p.TraceConnect4,
		p.TraceConnect6,
		p.TraceConnectionIngress,
		p.TraceDns,
		p.TraceExecve,
		p.TraceExecveat,
		p.TracePostBind4,
		p.TracePostBind6,
		p.TraceRecvmsg4,
		p.TraceRecvmsg6,
		p.TraceSendmsg4,
		p.TraceSendmsg6,
	)
}

func _TraceguardRecvmsgCompatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed traceguardrecvmsgcompat_bpfeb.o
var _TraceguardRecvmsgCompatBytes []byte
