// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type traceguardLinux71DNSCompatConnectionDedupeKey struct {
	_         structs.HostLayout
	Pid       uint32
	Port      uint16
	LocalPort uint16
	Family    uint8
	Protocol  uint8
	Direction uint8
	Pad       uint8
	Addr      [16]uint8
	LocalAddr [16]uint8
}

type traceguardLinux71DNSCompatConnectionDedupeValue struct {
	_          structs.HostLayout
	LastSeenNs uint64
}

type traceguardLinux71DNSCompatDnsParseResult struct {
	_                structs.HostLayout
	Key              traceguardLinux71DNSCompatDomainKey
	QnameLength      uint16
	AllowSuffixMatch uint8
	BlockSuffixMatch uint8
	Pad              [4]uint8
}

type traceguardLinux71DNSCompatDomainKey struct {
	_      structs.HostLayout
	Domain [256]uint8
}

type traceguardLinux71DNSCompatDomainSuffixKey struct {
	_          structs.HostLayout
	Hash       uint64
	Length     uint16
	PolicySlot uint8
	Pad0       uint8
	Pad1       uint32
}

type traceguardLinux71DNSCompatEgress4Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [21]uint8
	Pad       [3]uint8
}

type traceguardLinux71DNSCompatEgress6Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [33]uint8
	Pad       [3]uint8
}

type traceguardLinux71DNSCompatEndpoint4CidrKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [7]uint8
	Pad       uint8
}

type traceguardLinux71DNSCompatEndpoint4Key struct {
	_         structs.HostLayout
	Addr      uint32
	Port      uint16
	Transport uint8
	Pad       uint8
}

type traceguardLinux71DNSCompatEndpoint6CidrKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [19]uint8
	Pad       uint8
}

type traceguardLinux71DNSCompatEndpoint6Key struct {
	_         structs.HostLayout
	Addr      [16]uint8
	Port      uint16
	Transport uint8
	Pad       uint8
}

type traceguardLinux71DNSCompatListenerInfoKey struct {
	_        structs.HostLayout
	Port     uint16
	Family   uint8
	Protocol uint8
	Addr     [16]uint8
}

type traceguardLinux71DNSCompatListenerInfoValue struct {
	_    structs.HostLayout
	Pid  uint32
	Comm [16]int8
}

type traceguardLinux71DNSCompatSettings struct {
	_                    structs.HostLayout
	BlockEnabled         uint8
	BlockAllDomains      uint8
	BlockAllResolvers    uint8
	AllowSuffixesEnabled uint8
	ActivePolicySlot     uint8
	BlockSuffixesEnabled uint8
	EgressEnabled        uint8
	EgressEnforce        uint8
	EgressDefaultBlock   uint8
	Pad                  [7]uint8
}

type traceguardLinux71DNSCompatSocketInfoKey struct {
	_        structs.HostLayout
	Pid      uint32
	Port     uint16
	Family   uint8
	Protocol uint8
	Addr     [16]uint8
}

type traceguardLinux71DNSCompatSocketInfoValue struct {
	_        structs.HostLayout
	Comm     [16]int8
	Hook     uint8
	Family   uint8
	Protocol uint8
	Pad      uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	traceguardLinux71DNSCompatMapAllowSuffixes           = "allow_suffixes"
	traceguardLinux71DNSCompatMapAllowlist               = "allowlist"
	traceguardLinux71DNSCompatMapBlockSuffixes           = "block_suffixes"
	traceguardLinux71DNSCompatMapBlocklist               = "blocklist"
	traceguardLinux71DNSCompatMapConnectionDedupe        = "connection_dedupe"
	traceguardLinux71DNSCompatMapDnsScratch              = "dns_scratch"
	traceguardLinux71DNSCompatMapEgress4AllowRules       = "egress4_allow_rules"
	traceguardLinux71DNSCompatMapEgress4BlockRules       = "egress4_block_rules"
	traceguardLinux71DNSCompatMapEgress6AllowRules       = "egress6_allow_rules"
	traceguardLinux71DNSCompatMapEgress6BlockRules       = "egress6_block_rules"
	traceguardLinux71DNSCompatMapEndpoint4AllowRules     = "endpoint4_allow_rules"
	traceguardLinux71DNSCompatMapEndpoint4CidrAllowRules = "endpoint4_cidr_allow_rules"
	traceguardLinux71DNSCompatMapEndpoint4CidrRules      = "endpoint4_cidr_rules"
	traceguardLinux71DNSCompatMapEndpoint4Rules          = "endpoint4_rules"
	traceguardLinux71DNSCompatMapEndpoint6AllowRules     = "endpoint6_allow_rules"
	traceguardLinux71DNSCompatMapEndpoint6CidrAllowRules = "endpoint6_cidr_allow_rules"
	traceguardLinux71DNSCompatMapEndpoint6CidrRules      = "endpoint6_cidr_rules"
	traceguardLinux71DNSCompatMapEndpoint6Rules          = "endpoint6_rules"
	traceguardLinux71DNSCompatMapEvents                  = "events"
	traceguardLinux71DNSCompatMapListenerInfo            = "listener_info"
	traceguardLinux71DNSCompatMapSettings                = "settings"
	traceguardLinux71DNSCompatMapSocketInfo              = "socket_info"
	traceguardLinux71DNSCompatProgTraceConnect4          = "trace_connect4"
	traceguardLinux71DNSCompatProgTraceConnect6          = "trace_connect6"
	traceguardLinux71DNSCompatProgTraceConnectionIngress = "trace_connection_ingress"
	traceguardLinux71DNSCompatProgTraceCreat             = "trace_creat"
	traceguardLinux71DNSCompatProgTraceDns               = "trace_dns"
	traceguardLinux71DNSCompatProgTraceExecve            = "trace_execve"
	traceguardLinux71DNSCompatProgTraceExecveat          = "trace_execveat"
	traceguardLinux71DNSCompatProgTraceOpen              = "trace_open"
	traceguardLinux71DNSCompatProgTraceOpenat            = "trace_openat"
	traceguardLinux71DNSCompatProgTraceOpenat2           = "trace_openat2"
	traceguardLinux71DNSCompatProgTracePostBind4         = "trace_post_bind4"
	traceguardLinux71DNSCompatProgTracePostBind6         = "trace_post_bind6"
	traceguardLinux71DNSCompatProgTraceRecvmsg4          = "trace_recvmsg4"
	traceguardLinux71DNSCompatProgTraceRecvmsg6          = "trace_recvmsg6"
	traceguardLinux71DNSCompatProgTraceSendmsg4          = "trace_sendmsg4"
	traceguardLinux71DNSCompatProgTraceSendmsg6          = "trace_sendmsg6"
)

// loadTraceguardLinux71DNSCompat returns the embedded CollectionSpec for traceguardLinux71DNSCompat.
func loadTraceguardLinux71DNSCompat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TraceguardLinux71DNSCompatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load traceguardLinux71DNSCompat: %w", err)
	}

	return spec, err
}

// loadTraceguardLinux71DNSCompatObjects loads traceguardLinux71DNSCompat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*traceguardLinux71DNSCompatObjects
//	*traceguardLinux71DNSCompatPrograms
//	*traceguardLinux71DNSCompatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTraceguardLinux71DNSCompatObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTraceguardLinux71DNSCompat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// traceguardLinux71DNSCompatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardLinux71DNSCompatSpecs struct {
	traceguardLinux71DNSCompatProgramSpecs
	traceguardLinux71DNSCompatMapSpecs
	traceguardLinux71DNSCompatVariableSpecs
}

// traceguardLinux71DNSCompatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardLinux71DNSCompatProgramSpecs struct {
	TraceConnect4          *ebpf.ProgramSpec `ebpf:"trace_connect4"`
	TraceConnect6          *ebpf.ProgramSpec `ebpf:"trace_connect6"`
	TraceConnectionIngress *ebpf.ProgramSpec `ebpf:"trace_connection_ingress"`
	TraceCreat             *ebpf.ProgramSpec `ebpf:"trace_creat"`
	TraceDns               *ebpf.ProgramSpec `ebpf:"trace_dns"`
	TraceExecve            *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceExecveat          *ebpf.ProgramSpec `ebpf:"trace_execveat"`
	TraceOpen              *ebpf.ProgramSpec `ebpf:"trace_open"`
	TraceOpenat            *ebpf.ProgramSpec `ebpf:"trace_openat"`
	TraceOpenat2           *ebpf.ProgramSpec `ebpf:"trace_openat2"`
	TracePostBind4         *ebpf.ProgramSpec `ebpf:"trace_post_bind4"`
	TracePostBind6         *ebpf.ProgramSpec `ebpf:"trace_post_bind6"`
	TraceRecvmsg4          *ebpf.ProgramSpec `ebpf:"trace_recvmsg4"`
	TraceRecvmsg6          *ebpf.ProgramSpec `ebpf:"trace_recvmsg6"`
	TraceSendmsg4          *ebpf.ProgramSpec `ebpf:"trace_sendmsg4"`
	TraceSendmsg6          *ebpf.ProgramSpec `ebpf:"trace_sendmsg6"`
}

// traceguardLinux71DNSCompatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardLinux71DNSCompatMapSpecs struct {
	AllowSuffixes           *ebpf.MapSpec `ebpf:"allow_suffixes"`
	Allowlist               *ebpf.MapSpec `ebpf:"allowlist"`
	BlockSuffixes           *ebpf.MapSpec `ebpf:"block_suffixes"`
	Blocklist               *ebpf.MapSpec `ebpf:"blocklist"`
	ConnectionDedupe        *ebpf.MapSpec `ebpf:"connection_dedupe"`
	DnsScratch              *ebpf.MapSpec `ebpf:"dns_scratch"`
	Egress4AllowRules       *ebpf.MapSpec `ebpf:"egress4_allow_rules"`
	Egress4BlockRules       *ebpf.MapSpec `ebpf:"egress4_block_rules"`
	Egress6AllowRules       *ebpf.MapSpec `ebpf:"egress6_allow_rules"`
	Egress6BlockRules       *ebpf.MapSpec `ebpf:"egress6_block_rules"`
	Endpoint4AllowRules     *ebpf.MapSpec `ebpf:"endpoint4_allow_rules"`
	Endpoint4CidrAllowRules *ebpf.MapSpec `ebpf:"endpoint4_cidr_allow_rules"`
	Endpoint4CidrRules      *ebpf.MapSpec `ebpf:"endpoint4_cidr_rules"`
	Endpoint4Rules          *ebpf.MapSpec `ebpf:"endpoint4_rules"`
	Endpoint6AllowRules     *ebpf.MapSpec `ebpf:"endpoint6_allow_rules"`
	Endpoint6CidrAllowRules *ebpf.MapSpec `ebpf:"endpoint6_cidr_allow_rules"`
	Endpoint6CidrRules      *ebpf.MapSpec `ebpf:"endpoint6_cidr_rules"`
	Endpoint6Rules          *ebpf.MapSpec `ebpf:"endpoint6_rules"`
	Events                  *ebpf.MapSpec `ebpf:"events"`
	ListenerInfo            *ebpf.MapSpec `ebpf:"listener_info"`
	Settings                *ebpf.MapSpec `ebpf:"settings"`
	SocketInfo              *ebpf.MapSpec `ebpf:"socket_info"`
}

// traceguardLinux71DNSCompatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardLinux71DNSCompatVariableSpecs struct {
}

// traceguardLinux71DNSCompatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardLinux71DNSCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardLinux71DNSCompatObjects struct {
	traceguardLinux71DNSCompatPrograms
	traceguardLinux71DNSCompatMaps
	traceguardLinux71DNSCompatVariables
}

func (o *traceguardLinux71DNSCompatObjects) Close() error {
	return _TraceguardLinux71DNSCompatClose(
		&o.traceguardLinux71DNSCompatPrograms,
		&o.traceguardLinux71DNSCompatMaps,
	)
}

// traceguardLinux71DNSCompatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardLinux71DNSCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardLinux71DNSCompatMaps struct {
	AllowSuffixes           *ebpf.Map `ebpf:"allow_suffixes"`
	Allowlist               *ebpf.Map `ebpf:"allowlist"`
	BlockSuffixes           *ebpf.Map `ebpf:"block_suffixes"`
	Blocklist               *ebpf.Map `ebpf:"blocklist"`
	ConnectionDedupe        *ebpf.Map `ebpf:"connection_dedupe"`
	DnsScratch              *ebpf.Map `ebpf:"dns_scratch"`
	Egress4AllowRules       *ebpf.Map `ebpf:"egress4_allow_rules"`
	Egress4BlockRules       *ebpf.Map `ebpf:"egress4_block_rules"`
	Egress6AllowRules       *ebpf.Map `ebpf:"egress6_allow_rules"`
	Egress6BlockRules       *ebpf.Map `ebpf:"egress6_block_rules"`
	Endpoint4AllowRules     *ebpf.Map `ebpf:"endpoint4_allow_rules"`
	Endpoint4CidrAllowRules *ebpf.Map `ebpf:"endpoint4_cidr_allow_rules"`
	Endpoint4CidrRules      *ebpf.Map `ebpf:"endpoint4_cidr_rules"`
	Endpoint4Rules          *ebpf.Map `ebpf:"endpoint4_rules"`
	Endpoint6AllowRules     *ebpf.Map `ebpf:"endpoint6_allow_rules"`
	Endpoint6CidrAllowRules *ebpf.Map `ebpf:"endpoint6_cidr_allow_rules"`
	Endpoint6CidrRules      *ebpf.Map `ebpf:"endpoint6_cidr_rules"`
	Endpoint6Rules          *ebpf.Map `ebpf:"endpoint6_rules"`
	Events                  *ebpf.Map `ebpf:"events"`
	ListenerInfo            *ebpf.Map `ebpf:"listener_info"`
	Settings                *ebpf.Map `ebpf:"settings"`
	SocketInfo              *ebpf.Map `ebpf:"socket_info"`
}

func (m *traceguardLinux71DNSCompatMaps) Close() error {
	return _TraceguardLinux71DNSCompatClose(
		m.AllowSuffixes,
		m.Allowlist,
		m.BlockSuffixes,
		m.Blocklist,
		m.ConnectionDedupe,
		m.DnsScratch,
		m.Egress4AllowRules,
		m.Egress4BlockRules,
		m.Egress6AllowRules,
		m.Egress6BlockRules,
		m.Endpoint4AllowRules,
		m.Endpoint4CidrAllowRules,
		m.Endpoint4CidrRules,
		m.Endpoint4Rules,
		m.Endpoint6AllowRules,
		m.Endpoint6CidrAllowRules,
		m.Endpoint6CidrRules,
		m.Endpoint6Rules,
		m.Events,
		m.ListenerInfo,
		m.Settings,
		m.SocketInfo,
	)
}

// traceguardLinux71DNSCompatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardLinux71DNSCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardLinux71DNSCompatVariables struct {
}

// traceguardLinux71DNSCompatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardLinux71DNSCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardLinux71DNSCompatPrograms struct {
	TraceConnect4          *ebpf.Program `ebpf:"trace_connect4"`
	TraceConnect6          *ebpf.Program `ebpf:"trace_connect6"`
	TraceConnectionIngress *ebpf.Program `ebpf:"trace_connection_ingress"`
	TraceCreat             *ebpf.Program `ebpf:"trace_creat"`
	TraceDns               *ebpf.Program `ebpf:"trace_dns"`
	TraceExecve            *ebpf.Program `ebpf:"trace_execve"`
	TraceExecveat          *ebpf.Program `ebpf:"trace_execveat"`
	TraceOpen              *ebpf.Program `ebpf:"trace_open"`
	TraceOpenat            *ebpf.Program `ebpf:"trace_openat"`
	TraceOpenat2           *ebpf.Program `ebpf:"trace_openat2"`
	TracePostBind4         *ebpf.Program `ebpf:"trace_post_bind4"`
	TracePostBind6         *ebpf.Program `ebpf:"trace_post_bind6"`
	TraceRecvmsg4          *ebpf.Program `ebpf:"trace_recvmsg4"`
	TraceRecvmsg6          *ebpf.Program `ebpf:"trace_recvmsg6"`
	TraceSendmsg4          *ebpf.Program `ebpf:"trace_sendmsg4"`
	TraceSendmsg6          *ebpf.Program `ebpf:"trace_sendmsg6"`
}

func (p *traceguardLinux71DNSCompatPrograms) Close() error {
	return _TraceguardLinux71DNSCompatClose(
		p.TraceConnect4,
		p.TraceConnect6,
		p.TraceConnectionIngress,
		p.TraceCreat,
		p.TraceDns,
		p.TraceExecve,
		p.TraceExecveat,
		p.TraceOpen,
		p.TraceOpenat,
		p.TraceOpenat2,
		p.TracePostBind4,
		p.TracePostBind6,
		p.TraceRecvmsg4,
		p.TraceRecvmsg6,
		p.TraceSendmsg4,
		p.TraceSendmsg6,
	)
}

func _TraceguardLinux71DNSCompatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed traceguardlinux71dnscompat_bpfel.o
var _TraceguardLinux71DNSCompatBytes []byte
