// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type traceguardLinux71DNSRecvmsgCompatConnectionDedupeKey struct {
	_         structs.HostLayout
	Pid       uint32
	Port      uint16
	LocalPort uint16
	Family    uint8
	Protocol  uint8
	Direction uint8
	Pad       uint8
	Addr      [16]uint8
	LocalAddr [16]uint8
}

type traceguardLinux71DNSRecvmsgCompatConnectionDedupeValue struct {
	_          structs.HostLayout
	LastSeenNs uint64
}

type traceguardLinux71DNSRecvmsgCompatDnsParseResult struct {
	_                structs.HostLayout
	Key              traceguardLinux71DNSRecvmsgCompatDomainKey
	QnameLength      uint16
	AllowSuffixMatch uint8
	Pad              [5]uint8
}

type traceguardLinux71DNSRecvmsgCompatDomainKey struct {
	_      structs.HostLayout
	Domain [256]uint8
}

type traceguardLinux71DNSRecvmsgCompatDomainSuffixKey struct {
	_          structs.HostLayout
	Hash       uint64
	Length     uint16
	PolicySlot uint8
	Pad0       uint8
	Pad1       uint32
}

type traceguardLinux71DNSRecvmsgCompatEndpoint4CidrKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [7]uint8
	Pad       uint8
}

type traceguardLinux71DNSRecvmsgCompatEndpoint4Key struct {
	_         structs.HostLayout
	Addr      uint32
	Port      uint16
	Transport uint8
	Pad       uint8
}

type traceguardLinux71DNSRecvmsgCompatEndpoint6CidrKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [19]uint8
	Pad       uint8
}

type traceguardLinux71DNSRecvmsgCompatEndpoint6Key struct {
	_         structs.HostLayout
	Addr      [16]uint8
	Port      uint16
	Transport uint8
	Pad       uint8
}

type traceguardLinux71DNSRecvmsgCompatListenerInfoKey struct {
	_        structs.HostLayout
	Port     uint16
	Family   uint8
	Protocol uint8
	Addr     [16]uint8
}

type traceguardLinux71DNSRecvmsgCompatListenerInfoValue struct {
	_    structs.HostLayout
	Pid  uint32
	Comm [16]int8
}

type traceguardLinux71DNSRecvmsgCompatSettings struct {
	_                    structs.HostLayout
	BlockEnabled         uint8
	BlockAllDomains      uint8
	BlockAllResolvers    uint8
	AllowSuffixesEnabled uint8
	ActivePolicySlot     uint8
	Pad                  [3]uint8
}

type traceguardLinux71DNSRecvmsgCompatSocketInfoKey struct {
	_        structs.HostLayout
	Pid      uint32
	Port     uint16
	Family   uint8
	Protocol uint8
	Addr     [16]uint8
}

type traceguardLinux71DNSRecvmsgCompatSocketInfoValue struct {
	_        structs.HostLayout
	Comm     [16]int8
	Hook     uint8
	Family   uint8
	Protocol uint8
	Pad      uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	traceguardLinux71DNSRecvmsgCompatMapAllowSuffixes           = "allow_suffixes"
	traceguardLinux71DNSRecvmsgCompatMapAllowlist               = "allowlist"
	traceguardLinux71DNSRecvmsgCompatMapBlocklist               = "blocklist"
	traceguardLinux71DNSRecvmsgCompatMapConnectionDedupe        = "connection_dedupe"
	traceguardLinux71DNSRecvmsgCompatMapDnsScratch              = "dns_scratch"
	traceguardLinux71DNSRecvmsgCompatMapEndpoint4AllowRules     = "endpoint4_allow_rules"
	traceguardLinux71DNSRecvmsgCompatMapEndpoint4CidrAllowRules = "endpoint4_cidr_allow_rules"
	traceguardLinux71DNSRecvmsgCompatMapEndpoint4CidrRules      = "endpoint4_cidr_rules"
	traceguardLinux71DNSRecvmsgCompatMapEndpoint4Rules          = "endpoint4_rules"
	traceguardLinux71DNSRecvmsgCompatMapEndpoint6AllowRules     = "endpoint6_allow_rules"
	traceguardLinux71DNSRecvmsgCompatMapEndpoint6CidrAllowRules = "endpoint6_cidr_allow_rules"
	traceguardLinux71DNSRecvmsgCompatMapEndpoint6CidrRules      = "endpoint6_cidr_rules"
	traceguardLinux71DNSRecvmsgCompatMapEndpoint6Rules          = "endpoint6_rules"
	traceguardLinux71DNSRecvmsgCompatMapEvents                  = "events"
	traceguardLinux71DNSRecvmsgCompatMapListenerInfo            = "listener_info"
	traceguardLinux71DNSRecvmsgCompatMapSettings                = "settings"
	traceguardLinux71DNSRecvmsgCompatMapSocketInfo              = "socket_info"
	traceguardLinux71DNSRecvmsgCompatProgTraceConnect4          = "trace_connect4"
	traceguardLinux71DNSRecvmsgCompatProgTraceConnect6          = "trace_connect6"
	traceguardLinux71DNSRecvmsgCompatProgTraceConnectionIngress = "trace_connection_ingress"
	traceguardLinux71DNSRecvmsgCompatProgTraceCreat             = "trace_creat"
	traceguardLinux71DNSRecvmsgCompatProgTraceDns               = "trace_dns"
	traceguardLinux71DNSRecvmsgCompatProgTraceExecve            = "trace_execve"
	traceguardLinux71DNSRecvmsgCompatProgTraceExecveat          = "trace_execveat"
	traceguardLinux71DNSRecvmsgCompatProgTraceOpen              = "trace_open"
	traceguardLinux71DNSRecvmsgCompatProgTraceOpenat            = "trace_openat"
	traceguardLinux71DNSRecvmsgCompatProgTraceOpenat2           = "trace_openat2"
	traceguardLinux71DNSRecvmsgCompatProgTracePostBind4         = "trace_post_bind4"
	traceguardLinux71DNSRecvmsgCompatProgTracePostBind6         = "trace_post_bind6"
	traceguardLinux71DNSRecvmsgCompatProgTraceRecvmsg4          = "trace_recvmsg4"
	traceguardLinux71DNSRecvmsgCompatProgTraceRecvmsg6          = "trace_recvmsg6"
	traceguardLinux71DNSRecvmsgCompatProgTraceSendmsg4          = "trace_sendmsg4"
	traceguardLinux71DNSRecvmsgCompatProgTraceSendmsg6          = "trace_sendmsg6"
)

// loadTraceguardLinux71DNSRecvmsgCompat returns the embedded CollectionSpec for traceguardLinux71DNSRecvmsgCompat.
func loadTraceguardLinux71DNSRecvmsgCompat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TraceguardLinux71DNSRecvmsgCompatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load traceguardLinux71DNSRecvmsgCompat: %w", err)
	}

	return spec, err
}

// loadTraceguardLinux71DNSRecvmsgCompatObjects loads traceguardLinux71DNSRecvmsgCompat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*traceguardLinux71DNSRecvmsgCompatObjects
//	*traceguardLinux71DNSRecvmsgCompatPrograms
//	*traceguardLinux71DNSRecvmsgCompatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTraceguardLinux71DNSRecvmsgCompatObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTraceguardLinux71DNSRecvmsgCompat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// traceguardLinux71DNSRecvmsgCompatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardLinux71DNSRecvmsgCompatSpecs struct {
	traceguardLinux71DNSRecvmsgCompatProgramSpecs
	traceguardLinux71DNSRecvmsgCompatMapSpecs
	traceguardLinux71DNSRecvmsgCompatVariableSpecs
}

// traceguardLinux71DNSRecvmsgCompatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardLinux71DNSRecvmsgCompatProgramSpecs struct {
	TraceConnect4          *ebpf.ProgramSpec `ebpf:"trace_connect4"`
	TraceConnect6          *ebpf.ProgramSpec `ebpf:"trace_connect6"`
	TraceConnectionIngress *ebpf.ProgramSpec `ebpf:"trace_connection_ingress"`
	TraceCreat             *ebpf.ProgramSpec `ebpf:"trace_creat"`
	TraceDns               *ebpf.ProgramSpec `ebpf:"trace_dns"`
	TraceExecve            *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceExecveat          *ebpf.ProgramSpec `ebpf:"trace_execveat"`
	TraceOpen              *ebpf.ProgramSpec `ebpf:"trace_open"`
	TraceOpenat            *ebpf.ProgramSpec `ebpf:"trace_openat"`
	TraceOpenat2           *ebpf.ProgramSpec `ebpf:"trace_openat2"`
	TracePostBind4         *ebpf.ProgramSpec `ebpf:"trace_post_bind4"`
	TracePostBind6         *ebpf.ProgramSpec `ebpf:"trace_post_bind6"`
	TraceRecvmsg4          *ebpf.ProgramSpec `ebpf:"trace_recvmsg4"`
	TraceRecvmsg6          *ebpf.ProgramSpec `ebpf:"trace_recvmsg6"`
	TraceSendmsg4          *ebpf.ProgramSpec `ebpf:"trace_sendmsg4"`
	TraceSendmsg6          *ebpf.ProgramSpec `ebpf:"trace_sendmsg6"`
}

// traceguardLinux71DNSRecvmsgCompatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardLinux71DNSRecvmsgCompatMapSpecs struct {
	AllowSuffixes           *ebpf.MapSpec `ebpf:"allow_suffixes"`
	Allowlist               *ebpf.MapSpec `ebpf:"allowlist"`
	Blocklist               *ebpf.MapSpec `ebpf:"blocklist"`
	ConnectionDedupe        *ebpf.MapSpec `ebpf:"connection_dedupe"`
	DnsScratch              *ebpf.MapSpec `ebpf:"dns_scratch"`
	Endpoint4AllowRules     *ebpf.MapSpec `ebpf:"endpoint4_allow_rules"`
	Endpoint4CidrAllowRules *ebpf.MapSpec `ebpf:"endpoint4_cidr_allow_rules"`
	Endpoint4CidrRules      *ebpf.MapSpec `ebpf:"endpoint4_cidr_rules"`
	Endpoint4Rules          *ebpf.MapSpec `ebpf:"endpoint4_rules"`
	Endpoint6AllowRules     *ebpf.MapSpec `ebpf:"endpoint6_allow_rules"`
	Endpoint6CidrAllowRules *ebpf.MapSpec `ebpf:"endpoint6_cidr_allow_rules"`
	Endpoint6CidrRules      *ebpf.MapSpec `ebpf:"endpoint6_cidr_rules"`
	Endpoint6Rules          *ebpf.MapSpec `ebpf:"endpoint6_rules"`
	Events                  *ebpf.MapSpec `ebpf:"events"`
	ListenerInfo            *ebpf.MapSpec `ebpf:"listener_info"`
	Settings                *ebpf.MapSpec `ebpf:"settings"`
	SocketInfo              *ebpf.MapSpec `ebpf:"socket_info"`
}

// traceguardLinux71DNSRecvmsgCompatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardLinux71DNSRecvmsgCompatVariableSpecs struct {
}

// traceguardLinux71DNSRecvmsgCompatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardLinux71DNSRecvmsgCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardLinux71DNSRecvmsgCompatObjects struct {
	traceguardLinux71DNSRecvmsgCompatPrograms
	traceguardLinux71DNSRecvmsgCompatMaps
	traceguardLinux71DNSRecvmsgCompatVariables
}

func (o *traceguardLinux71DNSRecvmsgCompatObjects) Close() error {
	return _TraceguardLinux71DNSRecvmsgCompatClose(
		&o.traceguardLinux71DNSRecvmsgCompatPrograms,
		&o.traceguardLinux71DNSRecvmsgCompatMaps,
	)
}

// traceguardLinux71DNSRecvmsgCompatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardLinux71DNSRecvmsgCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardLinux71DNSRecvmsgCompatMaps struct {
	AllowSuffixes           *ebpf.Map `ebpf:"allow_suffixes"`
	Allowlist               *ebpf.Map `ebpf:"allowlist"`
	Blocklist               *ebpf.Map `ebpf:"blocklist"`
	ConnectionDedupe        *ebpf.Map `ebpf:"connection_dedupe"`
	DnsScratch              *ebpf.Map `ebpf:"dns_scratch"`
	Endpoint4AllowRules     *ebpf.Map `ebpf:"endpoint4_allow_rules"`
	Endpoint4CidrAllowRules *ebpf.Map `ebpf:"endpoint4_cidr_allow_rules"`
	Endpoint4CidrRules      *ebpf.Map `ebpf:"endpoint4_cidr_rules"`
	Endpoint4Rules          *ebpf.Map `ebpf:"endpoint4_rules"`
	Endpoint6AllowRules     *ebpf.Map `ebpf:"endpoint6_allow_rules"`
	Endpoint6CidrAllowRules *ebpf.Map `ebpf:"endpoint6_cidr_allow_rules"`
	Endpoint6CidrRules      *ebpf.Map `ebpf:"endpoint6_cidr_rules"`
	Endpoint6Rules          *ebpf.Map `ebpf:"endpoint6_rules"`
	Events                  *ebpf.Map `ebpf:"events"`
	ListenerInfo            *ebpf.Map `ebpf:"listener_info"`
	Settings                *ebpf.Map `ebpf:"settings"`
	SocketInfo              *ebpf.Map `ebpf:"socket_info"`
}

func (m *traceguardLinux71DNSRecvmsgCompatMaps) Close() error {
	return _TraceguardLinux71DNSRecvmsgCompatClose(
		m.AllowSuffixes,
		m.Allowlist,
		m.Blocklist,
		m.ConnectionDedupe,
		m.DnsScratch,
		m.Endpoint4AllowRules,
		m.Endpoint4CidrAllowRules,
		m.Endpoint4CidrRules,
		m.Endpoint4Rules,
		m.Endpoint6AllowRules,
		m.Endpoint6CidrAllowRules,
		m.Endpoint6CidrRules,
		m.Endpoint6Rules,
		m.Events,
		m.ListenerInfo,
		m.Settings,
		m.SocketInfo,
	)
}

// traceguardLinux71DNSRecvmsgCompatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardLinux71DNSRecvmsgCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardLinux71DNSRecvmsgCompatVariables struct {
}

// traceguardLinux71DNSRecvmsgCompatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardLinux71DNSRecvmsgCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardLinux71DNSRecvmsgCompatPrograms struct {
	TraceConnect4          *ebpf.Program `ebpf:"trace_connect4"`
	TraceConnect6          *ebpf.Program `ebpf:"trace_connect6"`
	TraceConnectionIngress *ebpf.Program `ebpf:"trace_connection_ingress"`
	TraceCreat             *ebpf.Program `ebpf:"trace_creat"`
	TraceDns               *ebpf.Program `ebpf:"trace_dns"`
	TraceExecve            *ebpf.Program `ebpf:"trace_execve"`
	TraceExecveat          *ebpf.Program `ebpf:"trace_execveat"`
	TraceOpen              *ebpf.Program `ebpf:"trace_open"`
	TraceOpenat            *ebpf.Program `ebpf:"trace_openat"`
	TraceOpenat2           *ebpf.Program `ebpf:"trace_openat2"`
	TracePostBind4         *ebpf.Program `ebpf:"trace_post_bind4"`
	TracePostBind6         *ebpf.Program `ebpf:"trace_post_bind6"`
	TraceRecvmsg4          *ebpf.Program `ebpf:"trace_recvmsg4"`
	TraceRecvmsg6          *ebpf.Program `ebpf:"trace_recvmsg6"`
	TraceSendmsg4          *ebpf.Program `ebpf:"trace_sendmsg4"`
	TraceSendmsg6          *ebpf.Program `ebpf:"trace_sendmsg6"`
}

func (p *traceguardLinux71DNSRecvmsgCompatPrograms) Close() error {
	return _TraceguardLinux71DNSRecvmsgCompatClose(
		p.TraceConnect4,
		p.TraceConnect6,
		p.TraceConnectionIngress,
		p.TraceCreat,
		p.TraceDns,
		p.TraceExecve,
		p.TraceExecveat,
		p.TraceOpen,
		p.TraceOpenat,
		p.TraceOpenat2,
		p.TracePostBind4,
		p.TracePostBind6,
		p.TraceRecvmsg4,
		p.TraceRecvmsg6,
		p.TraceSendmsg4,
		p.TraceSendmsg6,
	)
}

func _TraceguardLinux71DNSRecvmsgCompatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed traceguardlinux71dnsrecvmsgcompat_bpfeb.o
var _TraceguardLinux71DNSRecvmsgCompatBytes []byte
