// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type traceguardDomainKey struct {
	_      structs.HostLayout
	Domain [256]int8
}

type traceguardEndpoint4Key struct {
	_         structs.HostLayout
	Addr      uint32
	Port      uint16
	Transport uint8
	Pad       uint8
}

type traceguardEndpoint6Key struct {
	_         structs.HostLayout
	Addr      [16]uint8
	Port      uint16
	Transport uint8
	Pad       uint8
}

type traceguardSettings struct {
	_            structs.HostLayout
	BlockEnabled uint8
	Pad          [7]uint8
}

// loadTraceguard returns the embedded CollectionSpec for traceguard.
func loadTraceguard() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TraceguardBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load traceguard: %w", err)
	}

	return spec, err
}

// loadTraceguardObjects loads traceguard and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*traceguardObjects
//	*traceguardPrograms
//	*traceguardMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTraceguardObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTraceguard()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// traceguardSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardSpecs struct {
	traceguardProgramSpecs
	traceguardMapSpecs
	traceguardVariableSpecs
}

// traceguardProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardProgramSpecs struct {
	TraceConnect4 *ebpf.ProgramSpec `ebpf:"trace_connect4"`
	TraceConnect6 *ebpf.ProgramSpec `ebpf:"trace_connect6"`
	TraceDns      *ebpf.ProgramSpec `ebpf:"trace_dns"`
	TraceExecve   *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceExecveat *ebpf.ProgramSpec `ebpf:"trace_execveat"`
}

// traceguardMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardMapSpecs struct {
	Allowlist           *ebpf.MapSpec `ebpf:"allowlist"`
	Blocklist           *ebpf.MapSpec `ebpf:"blocklist"`
	Endpoint4AllowRules *ebpf.MapSpec `ebpf:"endpoint4_allow_rules"`
	Endpoint4Rules      *ebpf.MapSpec `ebpf:"endpoint4_rules"`
	Endpoint6AllowRules *ebpf.MapSpec `ebpf:"endpoint6_allow_rules"`
	Endpoint6Rules      *ebpf.MapSpec `ebpf:"endpoint6_rules"`
	Events              *ebpf.MapSpec `ebpf:"events"`
	Settings            *ebpf.MapSpec `ebpf:"settings"`
}

// traceguardVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardVariableSpecs struct {
}

// traceguardObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardObjects struct {
	traceguardPrograms
	traceguardMaps
	traceguardVariables
}

func (o *traceguardObjects) Close() error {
	return _TraceguardClose(
		&o.traceguardPrograms,
		&o.traceguardMaps,
	)
}

// traceguardMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardMaps struct {
	Allowlist           *ebpf.Map `ebpf:"allowlist"`
	Blocklist           *ebpf.Map `ebpf:"blocklist"`
	Endpoint4AllowRules *ebpf.Map `ebpf:"endpoint4_allow_rules"`
	Endpoint4Rules      *ebpf.Map `ebpf:"endpoint4_rules"`
	Endpoint6AllowRules *ebpf.Map `ebpf:"endpoint6_allow_rules"`
	Endpoint6Rules      *ebpf.Map `ebpf:"endpoint6_rules"`
	Events              *ebpf.Map `ebpf:"events"`
	Settings            *ebpf.Map `ebpf:"settings"`
}

func (m *traceguardMaps) Close() error {
	return _TraceguardClose(
		m.Allowlist,
		m.Blocklist,
		m.Endpoint4AllowRules,
		m.Endpoint4Rules,
		m.Endpoint6AllowRules,
		m.Endpoint6Rules,
		m.Events,
		m.Settings,
	)
}

// traceguardVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardVariables struct {
}

// traceguardPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardPrograms struct {
	TraceConnect4 *ebpf.Program `ebpf:"trace_connect4"`
	TraceConnect6 *ebpf.Program `ebpf:"trace_connect6"`
	TraceDns      *ebpf.Program `ebpf:"trace_dns"`
	TraceExecve   *ebpf.Program `ebpf:"trace_execve"`
	TraceExecveat *ebpf.Program `ebpf:"trace_execveat"`
}

func (p *traceguardPrograms) Close() error {
	return _TraceguardClose(
		p.TraceConnect4,
		p.TraceConnect6,
		p.TraceDns,
		p.TraceExecve,
		p.TraceExecveat,
	)
}

func _TraceguardClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed traceguard_bpfeb.o
var _TraceguardBytes []byte
