// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type traceguardDNSRecvmsgCompatConnectionDedupeKey struct {
	_         structs.HostLayout
	Pid       uint32
	Port      uint16
	LocalPort uint16
	Family    uint8
	Protocol  uint8
	Direction uint8
	Pad       uint8
	Addr      [16]uint8
	LocalAddr [16]uint8
}

type traceguardDNSRecvmsgCompatConnectionDedupeValue struct {
	_          structs.HostLayout
	LastSeenNs uint64
}

type traceguardDNSRecvmsgCompatDnsParseResult struct {
	_                structs.HostLayout
	Key              traceguardDNSRecvmsgCompatDomainKey
	QnameLength      uint16
	AllowSuffixMatch uint8
	BlockSuffixMatch uint8
	Pad              [4]uint8
}

type traceguardDNSRecvmsgCompatDomainKey struct {
	_      structs.HostLayout
	Domain [256]uint8
}

type traceguardDNSRecvmsgCompatDomainSuffixKey struct {
	_          structs.HostLayout
	Hash       uint64
	Length     uint16
	PolicySlot uint8
	Pad0       uint8
	Pad1       uint32
}

type traceguardDNSRecvmsgCompatEgress4Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [21]uint8
	Pad       [3]uint8
}

type traceguardDNSRecvmsgCompatEgress6Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [33]uint8
	Pad       [3]uint8
}

type traceguardDNSRecvmsgCompatEndpoint4CidrKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [7]uint8
	Pad       uint8
}

type traceguardDNSRecvmsgCompatEndpoint4Key struct {
	_         structs.HostLayout
	Addr      uint32
	Port      uint16
	Transport uint8
	Pad       uint8
}

type traceguardDNSRecvmsgCompatEndpoint6CidrKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Data      [19]uint8
	Pad       uint8
}

type traceguardDNSRecvmsgCompatEndpoint6Key struct {
	_         structs.HostLayout
	Addr      [16]uint8
	Port      uint16
	Transport uint8
	Pad       uint8
}

type traceguardDNSRecvmsgCompatListenerInfoKey struct {
	_        structs.HostLayout
	Port     uint16
	Family   uint8
	Protocol uint8
	Addr     [16]uint8
}

type traceguardDNSRecvmsgCompatListenerInfoValue struct {
	_    structs.HostLayout
	Pid  uint32
	Comm [16]int8
}

type traceguardDNSRecvmsgCompatSettings struct {
	_                    structs.HostLayout
	BlockEnabled         uint8
	BlockAllDomains      uint8
	BlockAllResolvers    uint8
	AllowSuffixesEnabled uint8
	ActivePolicySlot     uint8
	BlockSuffixesEnabled uint8
	EgressEnabled        uint8
	EgressEnforce        uint8
	EgressDefaultBlock   uint8
	Pad                  [7]uint8
}

type traceguardDNSRecvmsgCompatSocketInfoKey struct {
	_        structs.HostLayout
	Pid      uint32
	Port     uint16
	Family   uint8
	Protocol uint8
	Addr     [16]uint8
}

type traceguardDNSRecvmsgCompatSocketInfoValue struct {
	_        structs.HostLayout
	Comm     [16]int8
	Hook     uint8
	Family   uint8
	Protocol uint8
	Pad      uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	traceguardDNSRecvmsgCompatMapAllowSuffixes           = "allow_suffixes"
	traceguardDNSRecvmsgCompatMapAllowlist               = "allowlist"
	traceguardDNSRecvmsgCompatMapBlockSuffixes           = "block_suffixes"
	traceguardDNSRecvmsgCompatMapBlocklist               = "blocklist"
	traceguardDNSRecvmsgCompatMapConnectionDedupe        = "connection_dedupe"
	traceguardDNSRecvmsgCompatMapDnsScratch              = "dns_scratch"
	traceguardDNSRecvmsgCompatMapEgress4AllowRules       = "egress4_allow_rules"
	traceguardDNSRecvmsgCompatMapEgress4BlockRules       = "egress4_block_rules"
	traceguardDNSRecvmsgCompatMapEgress6AllowRules       = "egress6_allow_rules"
	traceguardDNSRecvmsgCompatMapEgress6BlockRules       = "egress6_block_rules"
	traceguardDNSRecvmsgCompatMapEndpoint4AllowRules     = "endpoint4_allow_rules"
	traceguardDNSRecvmsgCompatMapEndpoint4CidrAllowRules = "endpoint4_cidr_allow_rules"
	traceguardDNSRecvmsgCompatMapEndpoint4CidrRules      = "endpoint4_cidr_rules"
	traceguardDNSRecvmsgCompatMapEndpoint4Rules          = "endpoint4_rules"
	traceguardDNSRecvmsgCompatMapEndpoint6AllowRules     = "endpoint6_allow_rules"
	traceguardDNSRecvmsgCompatMapEndpoint6CidrAllowRules = "endpoint6_cidr_allow_rules"
	traceguardDNSRecvmsgCompatMapEndpoint6CidrRules      = "endpoint6_cidr_rules"
	traceguardDNSRecvmsgCompatMapEndpoint6Rules          = "endpoint6_rules"
	traceguardDNSRecvmsgCompatMapEvents                  = "events"
	traceguardDNSRecvmsgCompatMapListenerInfo            = "listener_info"
	traceguardDNSRecvmsgCompatMapSettings                = "settings"
	traceguardDNSRecvmsgCompatMapSocketInfo              = "socket_info"
	traceguardDNSRecvmsgCompatProgTraceConnect4          = "trace_connect4"
	traceguardDNSRecvmsgCompatProgTraceConnect6          = "trace_connect6"
	traceguardDNSRecvmsgCompatProgTraceConnectionIngress = "trace_connection_ingress"
	traceguardDNSRecvmsgCompatProgTraceCreat             = "trace_creat"
	traceguardDNSRecvmsgCompatProgTraceDns               = "trace_dns"
	traceguardDNSRecvmsgCompatProgTraceExecve            = "trace_execve"
	traceguardDNSRecvmsgCompatProgTraceExecveat          = "trace_execveat"
	traceguardDNSRecvmsgCompatProgTraceOpen              = "trace_open"
	traceguardDNSRecvmsgCompatProgTraceOpenat            = "trace_openat"
	traceguardDNSRecvmsgCompatProgTraceOpenat2           = "trace_openat2"
	traceguardDNSRecvmsgCompatProgTracePostBind4         = "trace_post_bind4"
	traceguardDNSRecvmsgCompatProgTracePostBind6         = "trace_post_bind6"
	traceguardDNSRecvmsgCompatProgTraceRecvmsg4          = "trace_recvmsg4"
	traceguardDNSRecvmsgCompatProgTraceRecvmsg6          = "trace_recvmsg6"
	traceguardDNSRecvmsgCompatProgTraceSendmsg4          = "trace_sendmsg4"
	traceguardDNSRecvmsgCompatProgTraceSendmsg6          = "trace_sendmsg6"
)

// loadTraceguardDNSRecvmsgCompat returns the embedded CollectionSpec for traceguardDNSRecvmsgCompat.
func loadTraceguardDNSRecvmsgCompat() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TraceguardDNSRecvmsgCompatBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load traceguardDNSRecvmsgCompat: %w", err)
	}

	return spec, err
}

// loadTraceguardDNSRecvmsgCompatObjects loads traceguardDNSRecvmsgCompat and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*traceguardDNSRecvmsgCompatObjects
//	*traceguardDNSRecvmsgCompatPrograms
//	*traceguardDNSRecvmsgCompatMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTraceguardDNSRecvmsgCompatObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTraceguardDNSRecvmsgCompat()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// traceguardDNSRecvmsgCompatSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardDNSRecvmsgCompatSpecs struct {
	traceguardDNSRecvmsgCompatProgramSpecs
	traceguardDNSRecvmsgCompatMapSpecs
	traceguardDNSRecvmsgCompatVariableSpecs
}

// traceguardDNSRecvmsgCompatProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardDNSRecvmsgCompatProgramSpecs struct {
	TraceConnect4          *ebpf.ProgramSpec `ebpf:"trace_connect4"`
	TraceConnect6          *ebpf.ProgramSpec `ebpf:"trace_connect6"`
	TraceConnectionIngress *ebpf.ProgramSpec `ebpf:"trace_connection_ingress"`
	TraceCreat             *ebpf.ProgramSpec `ebpf:"trace_creat"`
	TraceDns               *ebpf.ProgramSpec `ebpf:"trace_dns"`
	TraceExecve            *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceExecveat          *ebpf.ProgramSpec `ebpf:"trace_execveat"`
	TraceOpen              *ebpf.ProgramSpec `ebpf:"trace_open"`
	TraceOpenat            *ebpf.ProgramSpec `ebpf:"trace_openat"`
	TraceOpenat2           *ebpf.ProgramSpec `ebpf:"trace_openat2"`
	TracePostBind4         *ebpf.ProgramSpec `ebpf:"trace_post_bind4"`
	TracePostBind6         *ebpf.ProgramSpec `ebpf:"trace_post_bind6"`
	TraceRecvmsg4          *ebpf.ProgramSpec `ebpf:"trace_recvmsg4"`
	TraceRecvmsg6          *ebpf.ProgramSpec `ebpf:"trace_recvmsg6"`
	TraceSendmsg4          *ebpf.ProgramSpec `ebpf:"trace_sendmsg4"`
	TraceSendmsg6          *ebpf.ProgramSpec `ebpf:"trace_sendmsg6"`
}

// traceguardDNSRecvmsgCompatMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardDNSRecvmsgCompatMapSpecs struct {
	AllowSuffixes           *ebpf.MapSpec `ebpf:"allow_suffixes"`
	Allowlist               *ebpf.MapSpec `ebpf:"allowlist"`
	BlockSuffixes           *ebpf.MapSpec `ebpf:"block_suffixes"`
	Blocklist               *ebpf.MapSpec `ebpf:"blocklist"`
	ConnectionDedupe        *ebpf.MapSpec `ebpf:"connection_dedupe"`
	DnsScratch              *ebpf.MapSpec `ebpf:"dns_scratch"`
	Egress4AllowRules       *ebpf.MapSpec `ebpf:"egress4_allow_rules"`
	Egress4BlockRules       *ebpf.MapSpec `ebpf:"egress4_block_rules"`
	Egress6AllowRules       *ebpf.MapSpec `ebpf:"egress6_allow_rules"`
	Egress6BlockRules       *ebpf.MapSpec `ebpf:"egress6_block_rules"`
	Endpoint4AllowRules     *ebpf.MapSpec `ebpf:"endpoint4_allow_rules"`
	Endpoint4CidrAllowRules *ebpf.MapSpec `ebpf:"endpoint4_cidr_allow_rules"`
	Endpoint4CidrRules      *ebpf.MapSpec `ebpf:"endpoint4_cidr_rules"`
	Endpoint4Rules          *ebpf.MapSpec `ebpf:"endpoint4_rules"`
	Endpoint6AllowRules     *ebpf.MapSpec `ebpf:"endpoint6_allow_rules"`
	Endpoint6CidrAllowRules *ebpf.MapSpec `ebpf:"endpoint6_cidr_allow_rules"`
	Endpoint6CidrRules      *ebpf.MapSpec `ebpf:"endpoint6_cidr_rules"`
	Endpoint6Rules          *ebpf.MapSpec `ebpf:"endpoint6_rules"`
	Events                  *ebpf.MapSpec `ebpf:"events"`
	ListenerInfo            *ebpf.MapSpec `ebpf:"listener_info"`
	Settings                *ebpf.MapSpec `ebpf:"settings"`
	SocketInfo              *ebpf.MapSpec `ebpf:"socket_info"`
}

// traceguardDNSRecvmsgCompatVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type traceguardDNSRecvmsgCompatVariableSpecs struct {
}

// traceguardDNSRecvmsgCompatObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardDNSRecvmsgCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardDNSRecvmsgCompatObjects struct {
	traceguardDNSRecvmsgCompatPrograms
	traceguardDNSRecvmsgCompatMaps
	traceguardDNSRecvmsgCompatVariables
}

func (o *traceguardDNSRecvmsgCompatObjects) Close() error {
	return _TraceguardDNSRecvmsgCompatClose(
		&o.traceguardDNSRecvmsgCompatPrograms,
		&o.traceguardDNSRecvmsgCompatMaps,
	)
}

// traceguardDNSRecvmsgCompatMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardDNSRecvmsgCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardDNSRecvmsgCompatMaps struct {
	AllowSuffixes           *ebpf.Map `ebpf:"allow_suffixes"`
	Allowlist               *ebpf.Map `ebpf:"allowlist"`
	BlockSuffixes           *ebpf.Map `ebpf:"block_suffixes"`
	Blocklist               *ebpf.Map `ebpf:"blocklist"`
	ConnectionDedupe        *ebpf.Map `ebpf:"connection_dedupe"`
	DnsScratch              *ebpf.Map `ebpf:"dns_scratch"`
	Egress4AllowRules       *ebpf.Map `ebpf:"egress4_allow_rules"`
	Egress4BlockRules       *ebpf.Map `ebpf:"egress4_block_rules"`
	Egress6AllowRules       *ebpf.Map `ebpf:"egress6_allow_rules"`
	Egress6BlockRules       *ebpf.Map `ebpf:"egress6_block_rules"`
	Endpoint4AllowRules     *ebpf.Map `ebpf:"endpoint4_allow_rules"`
	Endpoint4CidrAllowRules *ebpf.Map `ebpf:"endpoint4_cidr_allow_rules"`
	Endpoint4CidrRules      *ebpf.Map `ebpf:"endpoint4_cidr_rules"`
	Endpoint4Rules          *ebpf.Map `ebpf:"endpoint4_rules"`
	Endpoint6AllowRules     *ebpf.Map `ebpf:"endpoint6_allow_rules"`
	Endpoint6CidrAllowRules *ebpf.Map `ebpf:"endpoint6_cidr_allow_rules"`
	Endpoint6CidrRules      *ebpf.Map `ebpf:"endpoint6_cidr_rules"`
	Endpoint6Rules          *ebpf.Map `ebpf:"endpoint6_rules"`
	Events                  *ebpf.Map `ebpf:"events"`
	ListenerInfo            *ebpf.Map `ebpf:"listener_info"`
	Settings                *ebpf.Map `ebpf:"settings"`
	SocketInfo              *ebpf.Map `ebpf:"socket_info"`
}

func (m *traceguardDNSRecvmsgCompatMaps) Close() error {
	return _TraceguardDNSRecvmsgCompatClose(
		m.AllowSuffixes,
		m.Allowlist,
		m.BlockSuffixes,
		m.Blocklist,
		m.ConnectionDedupe,
		m.DnsScratch,
		m.Egress4AllowRules,
		m.Egress4BlockRules,
		m.Egress6AllowRules,
		m.Egress6BlockRules,
		m.Endpoint4AllowRules,
		m.Endpoint4CidrAllowRules,
		m.Endpoint4CidrRules,
		m.Endpoint4Rules,
		m.Endpoint6AllowRules,
		m.Endpoint6CidrAllowRules,
		m.Endpoint6CidrRules,
		m.Endpoint6Rules,
		m.Events,
		m.ListenerInfo,
		m.Settings,
		m.SocketInfo,
	)
}

// traceguardDNSRecvmsgCompatVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardDNSRecvmsgCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardDNSRecvmsgCompatVariables struct {
}

// traceguardDNSRecvmsgCompatPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTraceguardDNSRecvmsgCompatObjects or ebpf.CollectionSpec.LoadAndAssign.
type traceguardDNSRecvmsgCompatPrograms struct {
	TraceConnect4          *ebpf.Program `ebpf:"trace_connect4"`
	TraceConnect6          *ebpf.Program `ebpf:"trace_connect6"`
	TraceConnectionIngress *ebpf.Program `ebpf:"trace_connection_ingress"`
	TraceCreat             *ebpf.Program `ebpf:"trace_creat"`
	TraceDns               *ebpf.Program `ebpf:"trace_dns"`
	TraceExecve            *ebpf.Program `ebpf:"trace_execve"`
	TraceExecveat          *ebpf.Program `ebpf:"trace_execveat"`
	TraceOpen              *ebpf.Program `ebpf:"trace_open"`
	TraceOpenat            *ebpf.Program `ebpf:"trace_openat"`
	TraceOpenat2           *ebpf.Program `ebpf:"trace_openat2"`
	TracePostBind4         *ebpf.Program `ebpf:"trace_post_bind4"`
	TracePostBind6         *ebpf.Program `ebpf:"trace_post_bind6"`
	TraceRecvmsg4          *ebpf.Program `ebpf:"trace_recvmsg4"`
	TraceRecvmsg6          *ebpf.Program `ebpf:"trace_recvmsg6"`
	TraceSendmsg4          *ebpf.Program `ebpf:"trace_sendmsg4"`
	TraceSendmsg6          *ebpf.Program `ebpf:"trace_sendmsg6"`
}

func (p *traceguardDNSRecvmsgCompatPrograms) Close() error {
	return _TraceguardDNSRecvmsgCompatClose(
		p.TraceConnect4,
		p.TraceConnect6,
		p.TraceConnectionIngress,
		p.TraceCreat,
		p.TraceDns,
		p.TraceExecve,
		p.TraceExecveat,
		p.TraceOpen,
		p.TraceOpenat,
		p.TraceOpenat2,
		p.TracePostBind4,
		p.TracePostBind6,
		p.TraceRecvmsg4,
		p.TraceRecvmsg6,
		p.TraceSendmsg4,
		p.TraceSendmsg6,
	)
}

func _TraceguardDNSRecvmsgCompatClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed traceguarddnsrecvmsgcompat_bpfeb.o
var _TraceguardDNSRecvmsgCompatBytes []byte
